services:
  backend:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
  nginx:
    image: "nginx:latest"
    ports:
      - 8621:3000
    volumes:
      - ./container/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    links:
      - backend
